<?php

// Taglines from IMDb.com, mostly.
$quotes = array(
"Boy meets girl. Boy falls in love. Girl doesn't.",
"This is not a love story. This is a story about love.",
"It was almost like falling in love.",
"How fast do You want it?",
"2Cool", "2Bold", "2Sexy", "2Tuff",
"The new models are in.",
"Cross the line one more time.",
"Time waits for one man.",
"Go back to where it all started.",
"Find your voice.",
"Every moment is another chance.",
"Every moment is a chance to turn it around.",
"Lose Yourself in the music.",
"If the streets had a voice, this would be the story they'd tell.",
"1 Witness... 118 Minutes...",
"For a New York cop and his witness, the distance between life and death just got very short.",
"Life is the symptom. Death is the cure.",
"How do you save yourself when you're already dead?",
"What does it sound like when you die?",
"The traps come alive.",
"Death is a shortcut.",
"Let the games begin!",
"Live or die. Make your choice.",
"Every piece has a puzzle.",
"How much blood would you shed to stay alive?",
"How do you solve a puzzle with pieces missing?",
"Their saw isn't there to cut their chains, they are there to cut their feet.",
"Every puzzle has its pieces.",
"We dare you again...",
"New game. Different pieces.",
"Oh, yes. There will be blood.",
"The game continues.",
"Sometimes, rules are meant to be broken...",
"Like father, like daughter.",
"To the victor goes the spoils.",
"Every game has its loopholes...",
"Suffering, you haven't seen anything yet.",
"Pain: it's part of the puzzle. Blood: it's the price of freedom. Death: it's not that easy.",
"Legends never die.",
"Do you deserve to live?",
"It's a Trap",
"You think it is over... but the games have just begun.",
"The game comes full circle.",
"6 chances, 6 lessons. 6 choices.",
"Trust in him.",
"I will never lie to you again. Ever! Unless I say \"I'm fine\".",
"The last man on earth is not alone",
"Welcome to earth. Population 1.",
"This place is so dead",
"Better to be fake and happy than real and miserable.",
"They're rushing through the hours quick",
"The rush is on!",
"Boys will be boys... some longer than others.",
"Back then they were too young to know better. Now they have no excuse.",
"Some guys need a little extra time to mature.",
"The only criminal he can't catch is himself.",
"The first and most important rule of gun-running is: never get shot with your own merchandise.",
"got guns?",
"He sells guns... and he's making a killing.",
"Where there's a will, there's a weapon.",
"Seven names. Seven strangers. One secret.",
"Let in the unexpected.",
"In a city of millions, finding one can change your whole life.",
"Live every day like it's the best day of your life.",

);